package db

import "github.com/harish876/hypefx/components/props"

// TODO: PUT SQL Lite Enginer here

var GridData = props.GridData{
	{
		Id:       "authurmelo",
		Name:     "Arthur Melo",
		Status:   "inactive",
		Position: "Design Director",
		Email:    "authurmelo@example.com",
		Badges:   []string{"Design", "Product", "Marketing"},
		Img:      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80",
	},
	{
		Id:       "ameliaanderson",
		Name:     "Amelia. Anderson",
		Status:   "active",
		Position: "Lead Developer",
		Email:    "ameliaanderson@example.com",
		Badges:   []string{"Design", "Product", "Marketing"},
		Img:      "https://images.unsplash.com/photo-1531590878845-12627191e687?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80",
	},
	{
		Id:       "junior",
		Name:     "junior REIS",
		Status:   "active",
		Position: "Product Manager",
		Email:    "junior@example.com",
		Badges:   []string{"Design", "Product", "Marketing"},
		Img:      "https://images.unsplash.com/photo-1608174386344-80898cec6beb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
	},
	{
		Id:       "oliviawathan",
		Name:     "olivia Wathan",
		Status:   "active",
		Position: "Lead Designer",
		Email:    "junior@example.com",
		Badges:   []string{"Design"},
		Img:      "https://images.unsplash.com/photo-1488508872907-592763824245?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
	},
	{
		Id:       "mia",
		Name:     "Mia",
		Status:   "active",
		Position: "Graphic Designer",
		Email:    "mia@example.com",
		Badges:   []string{"Design"},
		Img:      "https://images.unsplash.com/photo-1499470932971-a90681ce8530?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
	},
	{
		Id:       "johnsmith",
		Name:     "John Smith",
		Status:   "Active",
		Position: "Software Engineer",
		Email:    "john@example.com",
		Badges:   []string{"Engineering"},
		Img:      "https://randomuser.me/api/portraits/men/1.jpg",
	},
	{
		Id:       "emilyjones",
		Name:     "Emily Jones",
		Status:   "Active",
		Position: "UX Designer",
		Email:    "emily@example.com",
		Badges:   []string{"Design"},
		Img:      "https://randomuser.me/api/portraits/women/1.jpg",
	},
	{Id: "davidbrown",
		Name:     "David Brown",
		Status:   "Active",
		Position: "Product Manager",
		Email:    "david@example.com",
		Badges:   []string{"Product"},
		Img:      "https://randomuser.me/api/portraits/men/2.jpg",
	},
	{Id: "sarahwilson",
		Name:     "Sarah Wilson",
		Status:   "Active",
		Position: "Marketing Specialist",
		Email:    "sarah@example.com",
		Badges:   []string{"Marketing"},
		Img:      "https://randomuser.me/api/portraits/women/2.jpg",
	},
	{Id: "michaelclark",
		Name:     "Michael Clark",
		Status:   "Active",
		Position: "Data Analyst",
		Email:    "michael@example.com",
		Badges:   []string{"Analytics"},
		Img:      "https://randomuser.me/api/portraits/men/3.jpg",
	},
	{Id: "laurasmith",
		Name:     "Laura Smith",
		Status:   "Active",
		Position: "Frontend Developer",
		Email:    "laura@example.com",
		Badges:   []string{"Engineering"},
		Img:      "https://randomuser.me/api/portraits/women/3.jpg",
	},
	{Id: "samuelwilson",
		Name:     "Samuel Wilson",
		Status:   "Active",
		Position: "Graphic Designer",
		Email:    "samuel@example.com",
		Badges:   []string{"Design"},
		Img:      "https://randomuser.me/api/portraits/men/4.jpg",
	},
	{Id: "jessicajones",
		Name:     "Jessica Jones",
		Status:   "Active",
		Position: "Content Writer",
		Email:    "jessica@example.com",
		Badges:   []string{"Marketing"},
		Img:      "https://randomuser.me/api/portraits/women/4.jpg",
	},
	{Id: "andrewdavis",
		Name:     "Andrew Davis",
		Status:   "Active",
		Position: "DevOps Engineer",
		Email:    "andrew@example.com",
		Badges:   []string{"Engineering"},
		Img:      "https://randomuser.me/api/portraits/men/5.jpg",
	},
	{Id: "elinawilliams",
		Name:     "Elina Williams",
		Status:   "Active",
		Position: "UI/UX Designer",
		Email:    "elina@example.com",
		Badges:   []string{"Design", "Product", "Marketing"},
		Img:      "https://randomuser.me/api/portraits/women/5.jpg",
	},
	{
		Id:       "jane_doe",
		Name:     "Jane Doe",
		Status:   "active",
		Position: "Software Engineer",
		Email:    "jane.doe@example.com",
		Badges:   []string{"Programming", "Backend", "Testing"},
		Img:      "https://images.unsplash.com/photo-1564135624576-c5c88640f235?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=80",
	},
	{
		Id:       "mark_smith",
		Name:     "Mark Smith",
		Status:   "active",
		Position: "Data Analyst",
		Email:    "mark.smith@example.com",
		Badges:   []string{"Data Analysis", "Statistics", "Python"},
		Img:      "https://images.unsplash.com/photo-1521724741161-8586baa63f2f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=80",
	},
	{
		Id:       "alice_wang",
		Name:     "Alice Wang",
		Status:   "active",
		Position: "UI/UX Designer",
		Email:    "alice.wang@example.com",
		Badges:   []string{"UI Design", "UX Design", "Prototyping"},
		Img:      "https://images.unsplash.com/photo-1566837924344-c24b9099a4fc?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=80",
	},
	{
		Id:       "john_jones",
		Name:     "John Jones",
		Status:   "active",
		Position: "Project Manager",
		Email:    "john.jones@example.com",
		Badges:   []string{"Project Management", "Leadership", "Communication"},
		Img:      "https://images.unsplash.com/photo-1584378455941-ef9a8f16d2b1?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=80",
	},
	{
		Id:       "sarah_brown",
		Name:     "Sarah Brown",
		Status:   "active",
		Position: "Data Scientist",
		Email:    "sarah.brown@example.com",
		Badges:   []string{"Machine Learning", "Data Analysis", "Python"},
		Img:      "https://images.unsplash.com/photo-1528701961058-5aa39eaa2b62?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=80",
	},
	{
		Id:       "alex_miller",
		Name:     "Alex Miller",
		Status:   "active",
		Position: "Software Developer",
		Email:    "alex.miller@example.com",
		Badges:   []string{"Web Development", "JavaScript", "React"},
		Img:      "https://images.unsplash.com/photo-1581536764708-e29370f32064?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=80",
	},
	{
		Id:       "emily_white",
		Name:     "Emily White",
		Status:   "active",
		Position: "Content Writer",
		Email:    "emily.white@example.com",
		Badges:   []string{"Writing", "Content Creation", "SEO"},
		Img:      "https://images.unsplash.com/photo-1519681393784-d120267933ba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=80",
	},
	{
		Id:       "michael_clark",
		Name:     "Michael Clark",
		Status:   "active",
		Position: "Business Analyst",
		Email:    "michael.clark@example.com",
		Badges:   []string{"Business Analysis", "Financial Analysis", "Data Visualization"},
		Img:      "https://images.unsplash.com/photo-1520528434213-8a10f11c9c6f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=80",
	},
	{
		Id:       "lisa_thompson",
		Name:     "Lisa Thompson",
		Status:   "active",
		Position: "HR Manager",
		Email:    "lisa.thompson@example.com",
		Badges:   []string{"Human Resources", "Recruitment", "Employee Relations"},
		Img:      "https://images.unsplash.com/photo-1504805572947-34fad45aed93?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=80",
	},
	{
		Id:       "david_garcia",
		Name:     "David Garcia",
		Status:   "active",
		Position: "Sales Manager",
		Email:    "david.garcia@example.com",
		Badges:   []string{"Sales", "Negotiation", "Customer Relationship"},
		Img:      "https://images.unsplash.com/photo-1542206395-9f65869abc74?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=80",
	},
}
