// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package dropdown

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"encoding/json"
	"fmt"
)

func optionsJSON(options []SelectOption) string {
	bytes, err := json.Marshal(options)
	if err != nil {
		return ""
	}
	return string(bytes)
}

func MultiSelect(options []SelectOption, defaultSelectedOptions []SelectOption, name string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("{ isMultiSelectOpen: false, selectedOptions: [] }"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/dropdown/multi_select.templ`, Line: 17, Col: 79}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" @click.away=\"isMultiSelectOpen = false\"><section class=\"flex flex-col w-full\" id=\"multiSelect\"><div class=\"w-full py-2\"><div x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("multiselect({items: %s, defaultItems: %s})", optionsJSON(options), optionsJSON(defaultSelectedOptions)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/dropdown/multi_select.templ`, Line: 21, Col: 130}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" x-init=\"onInit\" @focusout=\"handleBlur\" class=\"relative\"><div class=\"flex items-center justify-between border rounded-md relative pr-8 bg-white min-h-10\"><ul class=\"flex flex-wrap flex-row items-center w-full\"><template x-for=\"(selectedItem, idx) in selectedItems\"><li x-text=\"shortenedLabel(selectedItem.label, maxTagChars)\" @click=\"removeElementByIdx(idx)\" @keyup.backspace=\"removeElementByIdx(idx)\" @keyup.delete=\"removeElementByIdx(idx)\" tabindex=\"0\" class=\"cursor-pointer px-3 py-1 mx-1 my-1 text-xs text-indigo-500 rounded-full :bg-gray-800 bg-indigo-100/60 after:content-[&#39;x&#39;] after:ml-1.5 transition-all inline-flex items-center justify-center\"></li></template><input name=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/dropdown/multi_select.templ`, Line: 40, Col: 25}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" type=\"hidden\" x-bind:value=\"selectedItems.map(d =&gt; d.value)\"> <input x-ref=\"searchInput\" x-model=\"search\" @click=\"expanded = true\" @focusin=\"expanded = true\" @input=\"expanded = true\" @keyup.arrow-down=\"expanded = true; selectNextItem()\" @keyup.arrow-up=\"expanded = true; selectPrevItem()\" @keyup.escape=\"reset\" @keyup.enter=\"addActiveItem\" :placeholder=\"searchPlaceholder\" type=\"text\" class=\"w-full hidden rounded-md border-white bg-white text-sm text-gray-700\"> <svg @click=\"expanded = !expanded; expanded &amp;&amp; $refs.searchInput.focus()\" xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" stroke-width=\"0\" fill=\"#ccc\" :class=\"expanded &amp;&amp; &#39;rotate-180&#39;\" class=\"absolute right-2 top-1/2 -translate-y-1/2 cursor-pointer focus:outline-none\" tabindex=\"-1\"><path d=\"M12 17.414 3.293 8.707l1.414-1.414L12 14.586l7.293-7.293 1.414 1.414L12 17.414z\"></path></svg></ul></div><template x-if=\"expanded\"><ul x-ref=\"listBox\" class=\"w-full list-none border border-t-0 rounded-md focus:outline-none overflow-y-auto outline-none bg-white absolute left-0 bottom-100\" tabindex=\"0\" :style=\"listBoxStyle\"><template x-if=\"filteredItems.length\"><template x-for=\"(filteredItem, idx) in filteredItems\"><li x-text=\"shortenedLabel(filteredItem.label, maxItemChars)\" @click=\"handleItemClick(filteredItem)\" :class=\"idx === activeIndex &amp;&amp; &#39;bg-blue-500 text-grey-600&#39;\" :title=\"filteredItem.label\" class=\"hover:bg-blue-500 hover:text-white cursor-pointer px-2 py-2\"></li></template></template><template x-if=\"!filteredItems.length\"><li x-text=\"emptyText\" class=\"cursor-pointer px-2 py-2 text-gray-400\"></li></template></ul></template></div></div><script src=\"/js/multiselect.js\"></script></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
